global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'featurehub-api'
    static_configs:
      - targets: ['featurehub-api:8000']
    metrics_path: '/metrics'

  - job_name: 'dataguard-api'
    static_configs:
      - targets: ['dataguard-api:8001']
    metrics_path: '/metrics'
